# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b047ca2985bd54a03eec3c608b1eb460eccd627b02f4dd253e9e79a687e982416a39acdaca169f7e9b5c3aea5f9250aa64fb1969420deb854e80e039c00027d

test:
  secret_key_base: e07e18971bec2d62da21ea046ac76915fa0fc7cd1518829eb6b97203a1b4512c6190042c47f66934393a6b277e34d6d816b9e6d0a82c232b7b416796248d8964

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
